### ISSUE TITLE
Data not found for Andorra cities

### ISSUE THREAD

**Issue by macklus** [nofxx/geonames_local#10]
Hi:
when i select AD as download code (Andorra), appears error:
```
Traceback (most recent call last):
        5: from ./bin/geonames:10:in `<main>'
        4: from ./geonames_local/lib/geonames_local/cli.rb:160:in `work'
        3: from /usr/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
        2: from ./geonames_local/lib/geonames_local/cli.rb:160:in `block in work'
        1: from ./geonames_local/lib/geonames_local/cli.rb:104:in `work_spots'
./geonames_local/lib/geonames_local/models/mongodb.rb:23:in `batch': undefined method `each' for nil:NilClass (NoMethodError)

```

**Comment by nofxx** [comment]
Wow, 10 years later theres  new version! hehe
