### ISSUE TITLE
Command not found after install gem

### ISSUE THREAD

**Issue by enric612** [nofxx/geonames_local#8]
After install : gem install geonames 
I just tip : geonames init 
But command this triggers a command not found error.
I try with ruby 2.2 and 1.9 on windows and on linux.
Some help? Thanks!

**Comment by nofxx** [comment]
Hello @enric612 , are you installing gems locally or on system? Which OS?
My bet you're missing this line on your ~/profile

```
export GEM_HOME=~/.gem/ruby/2.2.0
export PATH="$GEM_HOME/bin:$PATH:/home/nofxx/.bin"
```

**Comment by enric612** [comment]
Localy, i had to install with development kit on windows and i install other dependencies (like georuby) to make geonames works.
Now i run geonames -c geonames.yml -v and this is the output:
(I have mongo db working with php and robomongo without any security enabled localy)
===============================
    c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/georuby-2.5.2/lib/geo_ruby/ewk/ewkb_parse
r.rb:155: warning: already initialized constant GeoRuby::SimpleFeatures::UnpackS
tructure::NDR
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/GeoRuby-1.3.4/lib/geo_ruby/simple_feature
s/ewkb_parser.rb:175: warning: previous definition of NDR was here
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/georuby-2.5.2/lib/geo_ruby/ewk/ewkb_parse
r.rb:156: warning: already initialized constant GeoRuby::SimpleFeatures::UnpackS
tructure::XDR
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/GeoRuby-1.3.4/lib/geo_ruby/simple_feature
s/ewkb_parser.rb:176: warning: previous definition of XDR was here
Geopolitical Local Start!
Loading config file...
W, [2015-08-20T21:14:56.952728 #4664]  WARN -- : Overwriting existing field _id
in class Nation.
Using Mongoid v4.0.2
Mongoid connecting to {:host=>"localhost", :name=>"geonames_local"}
Using adapter mongodb..
I, [2015-08-20T21:14:59.218401 #4664]  INFO -- :   MOPED: Could not resolve IP f
or: localhost:27017, delta is 2.234421, error class is #<Resolv::ResolvError: Re
solv::ResolvError>, retries is 0. Node is <Moped::Node resolved_address=nil> run
time: n/a
W, [2015-08-20T21:14:59.296524 #4664]  WARN -- :   MOPED: Could not resolve IP f
or: localhost:27017, delta is 2.312544, error class is #<Resolv::ResolvError: Re
solv::ResolvError>, retries is 1. Node is <Moped::Node resolved_address=nil> run
time: n/a
W, [2015-08-20T21:14:59.359025 #4664]  WARN -- :   MOPED: Could not resolve IP f
or: localhost:27017, delta is 2.375045, error class is #<Resolv::ResolvError: Re
solv::ResolvError>, retries is 2. Node is <Moped::Node resolved_address=nil> run
time: n/a
W, [2015-08-20T21:14:59.359025 #4664]  WARN -- :   MOPED: Retrying connection at
tempt 1 more time(s), nodes is [], seeds are [<Moped::Node resolved_address=nil>
], cluster is #<Moped::Cluster:34336980 @seeds=[<Moped::Node resolved_address=ni
l>]>. Error backtrace is ["c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/li
b/moped/cluster.rb:254:in `with_primary'", "c:/Ruby22-x64/lib/ruby/gems/2.2.0/ge
ms/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'",
 "c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:i
n `call'", "c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/retryab
le.rb:30:in `with_retry'", "c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/l
ib/moped/read_preference/primary.rb:54:in `with_node'", "c:/Ruby22-x64/lib/ruby/
gems/2.2.0/gems/moped-2.0.7/lib/moped/database.rb:72:in `command'", "c:/Ruby22-x
64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/query.rb:42:in `count'", "c:/R
uby22-x64/lib/ruby/gems/2.2.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb
:60:in `block in count'", "c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongoid-4.0.2/
lib/mongoid/contextual/mongo.rb:457:in `try_cache'", "c:/Ruby22-x64/lib/ruby/gem
s/2.2.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:60:in `count'", "c:in
 `count'", "c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongoid-4.0.2/lib/mongoid/fin
dable.rb:51:in `count'", "c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/geonames_local-
3.3.4/lib/geonames_local/models/mongodb.rb:53:in `nations_populated?'", "c:/Ruby
22-x64/lib/ruby/gems/2.2.0/gems/geonames_local-3.3.4/lib/geonames_local/cli.rb:1
59:in `work'", "c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/geonames_local-3.3.4/bin/
geonames:10:in `<top (required)>'", "c:/Ruby22-x64/bin/geonames:23:in `load'", "
c:/Ruby22-x64/bin/geonames:23:in `<main>'"]. runtime: n/a
I, [2015-08-20T21:14:59.671530 #4664]  INFO -- :   MOPED: Could not resolve IP f
or: localhost:27017, delta is 0.046876, error class is #<Resolv::ResolvError: Re
solv::ResolvError>, retries is 0. Node is <Moped::Node resolved_address=nil> run
time: n/a
W, [2015-08-20T21:14:59.734032 #4664]  WARN -- :   MOPED: Could not resolve IP f
or: localhost:27017, delta is 0.109378, error class is #<Resolv::ResolvError: Re
solv::ResolvError>, retries is 1. Node is <Moped::Node resolved_address=nil> run
time: n/a
W, [2015-08-20T21:14:59.796520 #4664]  WARN -- :   MOPED: Could not resolve IP f
or: localhost:27017, delta is 0.171866, error class is #<Resolv::ResolvError: Re
solv::ResolvError>, retries is 2. Node is <Moped::Node resolved_address=nil> run
time: n/a
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/cluster.rb:254:in `
with_primary': Could not connect to a primary node for replica set #<Moped::Clus
ter:34336980 @seeds=[<Moped::Node resolved_address=nil>]> (Moped::Errors::Connec
tionFailure)
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/read_p
reference/primary.rb:55:in `block in with_node'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/retrya
ble.rb:30:in `call'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/retrya
ble.rb:30:in `with_retry'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/retrya
ble.rb:39:in `rescue in with_retry'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/retrya
ble.rb:29:in `with_retry'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/read_p
reference/primary.rb:54:in `with_node'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/databa
se.rb:72:in `command'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/moped-2.0.7/lib/moped/query.
rb:42:in `count'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongoid-4.0.2/lib/mongoid/co
ntextual/mongo.rb:60:in `block in count'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongoid-4.0.2/lib/mongoid/co
ntextual/mongo.rb:457:in `try_cache'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongoid-4.0.2/lib/mongoid/co
ntextual/mongo.rb:60:in `count'
        from c:in `count'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongoid-4.0.2/lib/mongoid/fi
ndable.rb:51:in `count'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/geonames_local-3.3.4/lib/geo
names_local/models/mongodb.rb:53:in `nations_populated?'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/geonames_local-3.3.4/lib/geo
names_local/cli.rb:159:in `work'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/geonames_local-3.3.4/bin/geo
names:10:in `<top (required)>'
        from c:/Ruby22-x64/bin/geonames:23:in `load'
        from c:/Ruby22-x64/bin/geonames:23:in `<main>'

==================

**Comment by enric612** [comment]
OK I get this to work, but now after download things i get this output (large output):

Region: Virginia / VA
Prob com spot
Problem:
  Attempted to set a value for 'gid' which is not allowed on the model Region.
Summary:
  Without including Mongoid::Attributes::Dynamic in your model and the attribute
 does not already exist in the attributes hash, attempting to call Region#gid= f
or it is not allowed. This is also triggered by passing the attribute to any met
hod that accepts an attributes hash, and is raised instead of getting a NoMethod
Error.
Resolution:
  You can include Mongoid::Attributes::Dynamic if you expect to be writing value
s for undefined fields often. c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongoid-5.0
.0.beta/lib/mongoid/attributes/processing.rb:99:in `process_attribute'

**Comment by nofxx** [comment]
Ah, rubygems version was outdated. Please give it a gem update.
New one is 3.3.5.
